// Generated by gencpp from file project/racetrack.msg
// DO NOT EDIT!


#ifndef PROJECT_MESSAGE_RACETRACK_H
#define PROJECT_MESSAGE_RACETRACK_H

#include <ros/service_traits.h>


#include <project/racetrackRequest.h>
#include <project/racetrackResponse.h>


namespace project
{

struct racetrack
{

typedef racetrackRequest Request;
typedef racetrackResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct racetrack
} // namespace project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::project::racetrack > {
  static const char* value()
  {
    return "b1133b6668b2500e671959e11f3eee47";
  }

  static const char* value(const ::project::racetrack&) { return value(); }
};

template<>
struct DataType< ::project::racetrack > {
  static const char* value()
  {
    return "project/racetrack";
  }

  static const char* value(const ::project::racetrack&) { return value(); }
};


// service_traits::MD5Sum< ::project::racetrackRequest> should match
// service_traits::MD5Sum< ::project::racetrack >
template<>
struct MD5Sum< ::project::racetrackRequest>
{
  static const char* value()
  {
    return MD5Sum< ::project::racetrack >::value();
  }
  static const char* value(const ::project::racetrackRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::project::racetrackRequest> should match
// service_traits::DataType< ::project::racetrack >
template<>
struct DataType< ::project::racetrackRequest>
{
  static const char* value()
  {
    return DataType< ::project::racetrack >::value();
  }
  static const char* value(const ::project::racetrackRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::project::racetrackResponse> should match
// service_traits::MD5Sum< ::project::racetrack >
template<>
struct MD5Sum< ::project::racetrackResponse>
{
  static const char* value()
  {
    return MD5Sum< ::project::racetrack >::value();
  }
  static const char* value(const ::project::racetrackResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::project::racetrackResponse> should match
// service_traits::DataType< ::project::racetrack >
template<>
struct DataType< ::project::racetrackResponse>
{
  static const char* value()
  {
    return DataType< ::project::racetrack >::value();
  }
  static const char* value(const ::project::racetrackResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJECT_MESSAGE_RACETRACK_H
